version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    labels: ["dependencies"]
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    labels: ["dependencies"]
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    labels: ["dependencies"]
    schedule:
      interval: weekly
