---
# https://taskfile.dev

version: '3'

tasks:
  buildall:
    cmds:
      - for: ['php83']
        cmd: docker build -f Dockerfile.{{ .ITEM }} . --target dev --tag qlico-{{ .ITEM }}
    silent: true
