---
# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Display all tasks
    cmds:
      - task --list-all

  buildall:
    desc: Build latest Dockerfile for test pursoses only
    cmds:
      - for: ['php']
        cmd: docker build -f Dockerfile . --target dev --tag qlico-{{ .ITEM }}
    silent: true
